{{- if .Values.rbac.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "logging-operator.fullname" . }}
  namespace: {{ include "logging-operator.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "logging-operator.name" . }}
    helm.sh/chart: {{ include "logging-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ template "logging-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "logging-operator.name" . }}
    helm.sh/chart: {{ include "logging-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - alertmanagers
      - prometheuses
      - prometheuses/finalizers
      - alertmanagers/finalizers
      - servicemonitors
      - podmonitors
      - prometheusrules
      - podmonitors
    verbs:
      - '*'
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - list
      - watch
  - apiGroups:
      - logging.banzaicloud.io
    resources:
      - loggings
      - flows
      - clusterflows
      - outputs
      - clusteroutputs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - logging.banzaicloud.io
    resources:
      - loggings/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
      - apps
      - batch
      - extensions
      - policy
      - rbac.authorization.k8s.io
    resources:
      - namespaces
      - nodes
      - persistentvolumeclaims
      - pods
      - services
      - resourcequotas
      - replicationcontrollers
      - limitranges
      - persistentvolumeclaims
      - persistentvolumes
      - endpoints
      - secrets
      - configmaps
      - serviceaccounts
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
      - podsecuritypolicies
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
      - jobs
    verbs:
      - "*"
  - apiGroups:
      - extensions
      - policy
    resources:
      - podsecuritypolicies
    verbs:
      - list
      - get
  {{- if .Values.rbac.psp.enabled }}
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - psp.logging-operator
    verbs:
      - use
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "logging-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "logging-operator.name" . }}
    helm.sh/chart: {{ include "logging-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
subjects:
  - kind: ServiceAccount
    name: {{ template "logging-operator.fullname" . }}
    namespace: {{ include "logging-operator.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "logging-operator.fullname" . }}

  {{- end }}
